### ISSUE TITLE
LIFX HSBK colorspace doesn't mention a reference point or absolute scale

### ISSUE THREAD

**Issue by ekux44** [LIFX/lifx-sdk-android#2]
The sdk's documentation of the [LIFX HSBK colorspace](https://github.com/LIFX/lifx-sdk-android/blob/master/library/src/lifx/java/android/entities/LFXHSBKColor.java)
doesn't mention the reference whitepoint or absolute scale

The documentation should list the white point, max red, max green, and max red, and gamma curve in an absolute system such as [CIE_1931](http://en.wikipedia.org/wiki/CIE_1931_color_space), so that colors can be accurately converted to other colorspaces such as [Wide RGB](http://en.wikipedia.org/wiki/Wide-gamut_RGB_color_space) or accurately previewed on Android in [sRGB](http://en.wikipedia.org/wiki/SRGB)

**Comment by thiggins09** [comment]
Was a resolution reached here? I too am trying to determine how to map LIFX HSBK space to an absolute color space.
