### ISSUE TITLE
Memory leak in LFXRoutingTable due to faulty LFXSiteID.equals()

### ISSUE THREAD

**Issue by joakimar** [LIFX/lifx-sdk-android#23]
The equals() method should take Object as its argument type, or else it won't override the parent's equals method. This bug causes LFXRoutingTable to add multiple copies of the same LFXSiteID to its member "mutableSiteIDs", since none of them seem "equal".

This is a simple and obvious fix, and I'm happy to do it for you if you tell me how to submit my code for your review.

**Comment by Cakey123445** [comment]
Have to say I'm struggling to see the problem with equals() on the LfXSiteId object, in the class definition it provides an equals method that checks the array equivalency.

I can see a problem here:

    public void updateSiteID(LFXSiteID siteID) {
        if (mutableSiteIDs.contains(siteID)) {
            return;
        }
        mutableSiteIDs.add(siteID);
    }

In that the contains() of the array list will not check for equivalency on the siteId object itself, its only checking that they're the same object reference and so this function will fail and add multiple siteIDs, was this what you were referring to in your post?

Thx

**Comment by joakimar** [comment]
Your "fixed code" does indeed solve the problem, but I would say in a bad way.

ArrayList DOES use equivalence (calls equals()). But the method signature in LfxSiteId has the wrong signature, and is not picked up as an override to Object.equals(Object).

The proper fix is in LfxSiteId. Replace

    public boolean equals(LFXSiteID aSiteID) {
        if (aSiteID == null) {
            return false;
        }

        if (!LFXByteUtils.areByteArraysEqual(data, aSiteID.data)) {
            return false;
        }

        return true;
    }

with

    public boolean equals(Object aSiteID) {
        if (aSiteID == null) {
            return false;
        }

        if (!LFXByteUtils.areByteArraysEqual(data, ((LfxSiteId) aSiteID).data)) {
            return false;
        }

        return true;
    }

**Comment by Cakey123445** [comment]
Wouldn't say my fix was bad, however I get your point re equals() and it is a better fix. Used your fix.

**Comment by smarthall** [comment]
Thanks to @Cakey123445 and @joakimar for fixing this for us!
