### ISSUE TITLE
Unity plugin

### ISSUE THREAD

**Issue by yosun** [LIFX/lifx-sdk-android#28]
Hi - is there a Unity plugin available? (Looks like your Android app is in Unity)

**Comment by smarthall** [comment]
LIFX has not yet developed a plugin for Unity but it does sound like a really cool idea. We have released details on our LAN protocol so any developer should be able to build one now. You can read this documentation here: http://lan.developer.lifx.com/

If you do end up building one we would love to hear about it here: https://community.lifx.com/
